### ISSUE TITLE
Qual sua versão do node?

### ISSUE THREAD

**Issue by Dathin** [gabireze/bitcoin-twitter-bot#2]
Nem sempre nosso código é compatível com todas as versões do node, principalmente quando nossa codebase vai ficando idosa.

Adicione um arquivo nvmrc.

executa
`node -v >> .nvmrc`

e commita o arquivo gerado =)

**Comment by gabireze** [comment]
Atualizei para versão v20.11.0, que é a mais recente suportada pelo [AWS Lambda](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html) no momento.

Realizei o commit do arquivo .nvmrc neste commit específico: https://github.com/gabireze/bitcoin-twitter-bot/commit/bb818b30960c9250c43526ab30aa172882d7af43

Valeu pela dica 😄
